import './globals.css'
import 'react-toastify/dist/ReactToastify.css'
import { ToastContainer } from 'react-toastify'

import { Inter } from 'next/font/google'
import { Providers } from './providers'
import Header from '@/components/Header'
import { getServerSession } from 'next-auth'
import { authOptions } from './api/auth/[...nextauth]/route'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <main className="container mx-auto">
            <Header user={session?.user} />
            {children}
          </main>
          <ToastContainer />
        </Providers>
      </body>
    </html>
  )
}
